name = "zowi-ranking"
main = "src/index.js"
compatibility_date = "2025-01-01"

[vars]
GITHUB_REPO = "eduardomillan/ZowiDesktop"
GITHUB_BRANCH = "gh-pages"
GITHUB_PATH = "docs/ranking/ranking.json"

[triggers]
crons = ["*/5 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "zowi-ranking"
database_id = "4973ba2b-8f5b-4dc4-90a4-ef3314beb028"
